# -*- coding: utf-8 -*-
"""decisionTREE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hW7OLrJvswhWQpenz8tMFOvL3WOkT_yR
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE

# Load dataset
df = pd.read_csv("/content/drive/MyDrive/Skin type detection and product recommendation/Skin_Type_OG.csv")

# Split features and target
X = df.drop(columns=['Skin_Type'])
y = df['Skin_Type']

# Encode target if categorical
if y.dtype == 'object' or y.dtype.name == 'category':
    le = LabelEncoder()
    y_enc = le.fit_transform(y)
    class_labels = le.classes_
else:
    y_enc = y.values
    class_labels = np.unique(y_enc)
print("Classes:", class_labels)

# Separate categorical and numerical columns
cat_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()
num_cols = X.select_dtypes(include=[np.number]).columns.tolist()

# Preprocessing: OneHotEncode categorical, pass numerical
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols),
        ('num', 'passthrough', num_cols)
    ]
)

# Train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y_enc, test_size=0.2, random_state=42, stratify=y_enc
)

# Preprocess features
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

# Decision Tree model
dt = DecisionTreeClassifier(random_state=42)

# Hyperparameter tuning
param_grid = {
    'max_depth': [5, 10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Use original training data without SMOTE
grid_search = GridSearchCV(estimator=dt, param_grid=param_grid, cv=5, n_jobs=-1, scoring='accuracy')
grid_search.fit(X_train_encoded, y_train)

best_model = grid_search.best_estimator_
print("Best parameters:", grid_search.best_params_)

# Predictions and accuracy
y_pred = best_model.predict(X_test_encoded)
acc = accuracy_score(y_test, y_pred)
print("Decision Tree Accuracy:", acc)

# Add precision, recall, and f1-score
report = classification_report(y_test, y_pred, target_names=class_labels, output_dict=True)
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=class_labels))

# Print individual metrics
print(f"Accuracy: {report['accuracy']:.4f}")
# Assuming you want the weighted average for precision, recall, and f1-score
print(f"Precision (weighted avg): {report['weighted avg']['precision']:.4f}")
print(f"Recall (weighted avg): {report['weighted avg']['recall']:.4f}")
print(f"F1-Score (weighted avg): {report['weighted avg']['f1-score']:.4f}")

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_labels, yticklabels=class_labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# Feature importance
importances = best_model.feature_importances_
feature_names = preprocessor.get_feature_names_out()
feat_imp = pd.Series(importances, index=feature_names).sort_values(ascending=False)
plt.figure(figsize=(10,6))
feat_imp[:20].plot(kind='bar')
plt.title("Top 20 Feature Importances")
plt.show()

# Visualize the decision tree (small version)
plt.figure(figsize=(20,10))
plot_tree(best_model, feature_names=feature_names, class_names=class_labels, filled=True, max_depth=3, fontsize=10)
plt.title("Decision Tree Visualization (Top 3 Levels)")
plt.show()