# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Eu7d2JPgwVvZk5sbKPoG59qHG8g54-b
"""

# evaluate.py

def evaluate_model(model, X_val, y_val):
    loss, acc = model.evaluate(X_val, y_val)
    print(f"\nValidation Accuracy: {acc*100:.2f}%")
    return acc