# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahYriIuJypQs0S3vuMKqMyqjckl4l5a_
"""

import cv2
import matplotlib.pyplot as plt

IMG_SIZE = 256
img = cv2.imread("/content/drive/MyDrive/combination.jpg")
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB)) # Convert BGR to RGB for correct display

def preprocess_image(img):
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img.astype(int)/225
    return img



cv2.imwrite("output.jpg", preprocess_image(img))

# Load and display output.jpg
processed_img = cv2.imread("output.jpg")
plt.imshow(cv2.cvtColor(processed_img, cv2.COLOR_BGR2RGB))