# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBsa-1YCUc21ujTmpW22dVqQAOB9K_P3
"""

# main.py

from  models import build_model

def main():
    model, history, classes = build_model()

    print("Classes:", classes)

if __name__ == "__main__":
    main()

with open('cnn_model.py', 'r') as f:
    print(f.read())

"""# New section"""