# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RhdRttEfpJbgJeA3xtX2KdskXmnDcuEu
"""

# src/model.py

from tensorflow.keras import layers, models

def build_model(input_shape=(128, 128, 3), num_classes=3):

    model = models.Sequential([

        # 👇 Proper input layer (fixes your earlier warning)
        layers.Input(shape=input_shape),

        # Block 1
        layers.Conv2D(32, (3,3), activation='relu'),
        layers.MaxPooling2D(2,2),

        # Block 2
        layers.Conv2D(64, (3,3), activation='relu'),
        layers.MaxPooling2D(2,2),

        # Block 3
        layers.Conv2D(128, (3,3), activation='relu'),
        layers.MaxPooling2D(2,2),

        # 👇 Better than Flatten (reduces overfitting risk)
        layers.GlobalAveragePooling2D(),

        # Classifier
        layers.Dense(128, activation='relu'),
        layers.Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    return model