# -*- coding: utf-8 -*-
"""Random Forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3QnBUSVZIrlRkq74bTYQvl1JuhYDYDd
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load datasets
df = pd.read_csv("/content/drive/MyDrive/Skin type detection and product recommendation/Skin_Type_OG.csv")

# Use Skin_Type from df1 as target, drop Skin_Type_y from df2

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load datasets
df = pd.read_csv("/content/drive/MyDrive/Skin type detection and product recommendation/Skin_Type_OG.csv")

df

from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Identify categorical feature columns (excluding target)
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()
#categorical_cols.remove("Skin_Type")  # exclude target

# One-hot encode categorical features
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Encode target separately (since it's multiclass)
target_encoder = LabelEncoder()
df["Skin_Type"] = target_encoder.fit_transform(df["Skin_Type"])

# Features and target
X = df.drop(columns=["Skin_Type"])
y = df["Skin_Type"]

rf_model = RandomForestClassifier(n_estimators=200, random_state=42)

# Apply cross-validation
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score

# Define scoring metrics
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted'),
    'recall': make_scorer(recall_score, average='weighted'),
    'f1_score': make_scorer(f1_score, average='weighted')
}

cv_results = cross_validate(rf_model, X, y, cv=10, scoring=scoring) # 5-fold cross-validation

print("Cross-validation results:")
for metric_name, scores in cv_results.items():
    if metric_name.startswith('test_'):
        print(f"{metric_name[5:].capitalize()} scores: {scores}")
        print(f"Mean {metric_name[5:].capitalize()} accuracy: {scores.mean()}")

rf_model.fit(X, y)
importances = rf_model.feature_importances_
for col, imp in sorted(zip(X.columns, importances), key=lambda x: x[1], reverse=True):
    print(col, imp)

import matplotlib.pyplot as plt
import seaborn as sns

# Create the histogram
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='Oil_Level', hue='Skin_Type', multiple='dodge', shrink=0.8)

# Display the plot
plt.title('Distribution of Oil Level by Skin Type')
plt.xlabel('Oil Level')
plt.ylabel('Frequency')
plt.show()



import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Get feature importances from the trained model
importances = rf_model.feature_importances_

print(importances)

# Create a DataFrame for easier plotting
feature_importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
})

# Sort by importance
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Create the bar plot
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df)

# Display the plot
plt.title('Feature Importances')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.show()

categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

encoder = LabelEncoder()
for col in categorical_cols:
   df[col] = encoder.fit_transform(df[col])

# Encode target separately
target_encoder = LabelEncoder()
df["Skin_Type"] = target_encoder.fit_transform(df["Skin_Type"])

# Features and target
X = df.drop(columns=["Skin_Type"])
y = df["Skin_Type"]

rf_model = RandomForestClassifier(n_estimators=200, random_state=42)

# Apply cross-validation
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score

# Define scoring metrics
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted'),
    'recall': make_scorer(recall_score, average='weighted'),
    'f1_score': make_scorer(f1_score, average='weighted')
}

cv_results = cross_validate(rf_model, X, y, cv=5, scoring=scoring) # 5-fold cross-validation

print("Cross-validation results:")
for metric_name, scores in cv_results.items():
    if metric_name.startswith('test_'):
        print(f"{metric_name[5:].capitalize()} scores: {scores}")
        print(f"Mean {metric_name[5:].capitalize()} accuracy: {scores.mean()}")

import matplotlib.pyplot as plt
import seaborn as sns

# Plot the confusion matrix as a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted Skin Type')
plt.ylabel('True Skin Type')
plt.title('Confusion Matrix')
plt.show()

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict

# Get predictions for each fold
y_pred = cross_val_predict(rf_model, X, y, cv=5)

# Calculate and display confusion matrix
conf_matrix = confusion_matrix(y, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print(y_pred)

"""# Task
Analyze the provided dataset to identify potential causes of overfitting and suggest strategies to mitigate it.

## Visualize data distributions

### Subtask:
Visualize the distribution of features and the target variable to check for any imbalances or issues that might contribute to overfitting.

**Reasoning**:
Create histograms for numerical features and bar plots for categorical features and the target variable to visualize their distributions.
"""

numerical_cols = df.select_dtypes(include=['number']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
target_col = 'Skin_Type'

# Plot histograms for numerical features
for col in numerical_cols:
    if col != target_col:
        plt.figure(figsize=(8, 6))
        sns.histplot(df[col], kde=True)
        plt.title(f'Distribution of {col}')
        plt.xlabel(col)
        plt.ylabel('Frequency')
        plt.show()

# Plot bar plots for categorical features
for col in categorical_cols:
    if col != target_col:
        plt.figure(figsize=(8, 6))
        df[col].value_counts().plot(kind='bar')
        plt.title(f'Distribution of {col}')
        plt.xlabel(col)
        plt.ylabel('Count')
        plt.xticks(rotation=0)
        plt.show()

# Plot bar plot for the target variable
plt.figure(figsize=(8, 6))
df[target_col].value_counts().plot(kind='bar')
plt.title(f'Distribution of {target_col}')
plt.xlabel(target_col)
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.show()

"""**Reasoning**:
The previous attempt failed because the dataframe 'df' was not defined in the current session. Reload the data and then proceed with plotting the distributions.


"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset again
df = pd.read_csv("/content/drive/MyDrive/Skin type detection and product recommendation/Skin_Type_OG.csv")

# Separate numerical, categorical, and target columns
numerical_cols = df.select_dtypes(include=['number']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
target_col = 'Skin_Type'

# Plot histograms for numerical features
for col in numerical_cols:
    if col != target_col:
        plt.figure(figsize=(8, 6))
        sns.histplot(df[col], kde=True)
        plt.title(f'Distribution of {col}')
        plt.xlabel(col)
        plt.ylabel('Frequency')
        plt.show()

# Plot bar plots for categorical features
for col in categorical_cols:
    if col != target_col:
        plt.figure(figsize=(8, 6))
        df[col].value_counts().plot(kind='bar')
        plt.title(f'Distribution of {col}')
        plt.xlabel(col)
        plt.ylabel('Count')
        plt.xticks(rotation=0)
        plt.show()

# Plot bar plot for the target variable
plt.figure(figsize=(8, 6))
df[target_col].value_counts().plot(kind='bar')
plt.title(f'Distribution of {target_col}')
plt.xlabel(target_col)
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.show()