# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11btKEcwBsR0FpGgBCbbgjFmoJtAWC0WU
"""

# src/train.py

from src.data_loader import load_images
from src.model import build_model

def train_model():

    # 🔹 Load data
    X_train, y_train, class_names = load_images("dataset/train")
    X_val, y_val, _ = load_images("dataset/val")

    print("Train shape:", X_train.shape)
    print("Val shape:", X_val.shape)

    # 🔹 Build model
    model = build_model()

    # 🔹 Train
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=10,
        batch_size=32
    )

    return model, history, class_names