# -*- coding: utf-8 -*-
"""XGBoost for skin_lifestyle_dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwHO9sm5EEPIKPqgL8hoJ3zonCWICkI4
"""

import pandas as pd
url = "Skin_Type_OG.csv'
df = pd.read_csv(url)
df

"""checking for missing values"""

# Check for missing values
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values)

df = df.drop(df.columns[0], axis=1)
df = df.drop_duplicates()
df.head()

# Examine unique values and their counts in 'Exercise_Frequency'
exercise_frequency_counts = df['Exercise_Frequency'].value_counts(dropna=False)
print("Distribution of Exercise_Frequency (including missing values):\n", exercise_frequency_counts)

# Check the percentage of missing values
missing_percentage = (df['Exercise_Frequency'].isnull().sum() / len(df)) * 100
print(f"\nPercentage of missing values in Exercise_Frequency: {missing_percentage:.2f}%")

# Impute missing values with the mode
mode_exercise_frequency = df['Exercise_Frequency'].mode()[0]
df['Exercise_Frequency'].fillna(mode_exercise_frequency, inplace=True)

print("\nMissing values in Exercise_Frequency after handling:\n", df['Exercise_Frequency'].isnull().sum())

"""describing the dataset"""

print(f"{df.info()}/n")
print(df.describe())

df

"""##Plots

Bar plot
"""

categorical_cols = ['Gender',	'Climate'	,'Lifestyle'	,'Skin_Type'	,'Diet', 'Stress_Level',	'Exercise_Frequency']
numerical_cols = [	'Age', 'Water_Intake_Liters' ,	'Sleep_Hours']

import seaborn as sns
import matplotlib.pyplot as plt

for col in numerical_cols:
  plt.subplot(111)
  plt.figure(figsize=(15, 5))
  sns.histplot(data=df, x=col, kde=True) #A single peak (bell curve) → most people have similar oiliness.Multiple peaks → there are distinct groups
     #(e.g., dry vs oily vs combination skin). if the feature shows constant distribution across all the variables you can prob just drop it
  plt.title(f'Distribution of {col}') # that wavy line is to smoothen out the distribution
  plt.xlabel(col)
  plt.ylabel('Frequency')
  plt.tight_layout()
  plt.show()

for cols in categorical_cols:
  for i in numerical_cols:
   # plt.figure(figsize=(15, 5))
    sns.boxplot(x=cols, y=i, data=df)
    plt.show()

"""### Correlation Matrix

In this case the matrix didnt contribute much to understanding the data , because it is understood that the features are weakly related .
"""

# Analyze relationships between numerical variables
numerical_cols = [	'Age', 'Water_Intake_Liters' ,	'Sleep_Hours']
correlation_matrix = df[numerical_cols].corr()

# Strong multicollinearity → basically duplicate features.Strong negative correlation → might cause redundancy. low correlation → ✅ provides unique information.
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Variables')
plt.show()
# if you find multicollinearity then combine the features , drop them ,so choose a model less sensitive to multicollinearity

# now a scaterplot to show relations between numerical variabes
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
sns.scatterplot(data=df, x='Age', y='Water_Intake_Liters')
plt.title('Age vs.Water_Intake_Liters ')
plt.subplot(1, 3, 2)
sns.scatterplot(data=df, x='Age', y='Sleep_Hours')
plt.title('Age vs. Sleep_Hours')
plt.subplot(1, 3, 3)
sns.scatterplot(data=df, x='Water_Intake_Liters', y='Sleep_Hours')
plt.title('Water_Intake_Liters vs. Sleep_Hours')
plt.tight_layout()
plt.show()

"""Barplots to analyse relationship between categorical variables

"""

import seaborn as sns
import matplotlib.pyplot as plt

categorical_cols = ['Gender',   'Climate'       ,'Lifestyle'    ,'Diet', 'Stress_Level',        'Exercise_Frequency']

for col in categorical_cols:
    plt.figure(figsize=(10, 6))
    sns.countplot(data=df, x=col, hue='Skin_Type')
    plt.title(f'Distribution of Skin Type by {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

# Handle outliers by capping (using IQR method)
numerical_cols = [	'Age', 'Water_Intake_Liters' ,	'Sleep_Hours']
outlier_counts = {}
df_capped = df.copy()

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outlier_counts[col] = len(outliers)

    df_capped[col] = df_capped[col].clip(lower=lower_bound, upper=upper_bound)

print("Number of outliers per column using IQR method:")
for col, count in outlier_counts.items():
    print(f"{col}: {count}")

print("\nOutliers handled by capping to the calculated lower and upper bounds.")

# Update df to the capped version for subsequent steps
df = df_capped.copy()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Define features (X) and target (y)
X = df.drop('Skin_Type', axis=1)
y = df['Skin_Type']

# Identify categorical and numerical features
categorical_features = ['Gender', 'Climate', 'Lifestyle', 'Diet', 'Stress_Level', 'Exercise_Frequency']
numerical_features = ['Age', 'Water_Intake_Liters', 'Sleep_Hours']

# Create a column transformer for one-hot encoding
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough' # Keep numerical features
)

# Apply the transformations to the features
X_encoded = preprocessor.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

print("Shape of original features:", X.shape)
print("Shape of encoded features:", X_encoded.shape)
print("Shape of training features:", X_train.shape)
print("Shape of testing features:", X_test.shape)
print("Shape of training target:", y_train.shape)
print("Shape of testing target:", y_test.shape)

from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

# XGBoost : numerical labels for the target variable so 'Skin_Type' should be encoded into numerical variable
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

xgb_model = XGBClassifier( eval_metric='merror',enable_categorical = True) # enable_categorical = True
xgb_model.fit(X_train, y_train_encoded)

print("XGBoost model training complete.")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Make predictions on the test set using the trained XGBoost model
y_pred_encoded = xgb_model.predict(X_test)

# Decode the predictions back to original labels
y_pred = label_encoder.inverse_transform(y_pred_encoded)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, y_pred_encoded)
print(f"Accuracy: {accuracy:.2f}")

# Print classification report
print("\nClassification Report:")
print(classification_report(y_test_encoded, y_pred_encoded, target_names=label_encoder.classes_))

# Generate and display the confusion matrix
cm = confusion_matrix(y_test_encoded, y_pred_encoded)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

import pandas as pd
import numpy as np

# Function to get user input for prediction
def get_user_input(categorical_features, numerical_features):
    user_data = {}
    print("Please provide the following information:")

    for col in numerical_features:
        while True:
            try:
                value = float(input(f"Enter your {col}: "))
                user_data[col] = value
                break
            except ValueError:
                print("Invalid input. Please enter a numerical value.")

    for col in categorical_features:
        while True:
            value = input(f"Enter your {col}: ")
            user_data[col] = value
            break

    # Add 'Person_ID' with a dummy value, as it's not used for prediction
    user_data['Person_ID'] = 0 # Or any other placeholder

    # Ensure all columns are present in the same order as the training data's original features
    # (excluding 'Skin_Type')
    input_df = pd.DataFrame([user_data], columns=[col for col in df.columns if col != 'Skin_Type'])
    return input_df

# Get user input
user_input_df = get_user_input(categorical_features, numerical_features)

# Apply the same preprocessing as done for the training data
# We need to handle the missing 'Exercise_Frequency' value in user input if applicable.
# For simplicity, we'll fill it with a placeholder that the one-hot encoder can handle.
# A more robust approach might involve asking the user or using imputation based on training data.
if 'Exercise_Frequency' in user_input_df.columns and user_input_df['Exercise_Frequency'].isnull().any():
    user_input_df['Exercise_Frequency'] = 'Unknown' # Or a more appropriate placeholder

user_input_encoded = preprocessor.transform(user_input_df)

# Predict the skin type
predicted_skin_type_encoded = xgb_model.predict(user_input_encoded)

# Decode the prediction back to the original label
predicted_skin_type = label_encoder.inverse_transform(predicted_skin_type_encoded)

print(f"\nBased on your inputs, your predicted skin type is: {predicted_skin_type[0]}")

"""# Task
Improve the accuracy of the XGBoost model for skin type classification by addressing data quality issues, performing feature engineering, handling class imbalance, tuning hyperparameters, and potentially trying different models. Evaluate the improvements using the classification report and cross-validation.
"""
