# -*- coding: utf-8 -*-
"""logistics_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5p2DsDCnsbg79ciRehm1gjLixkw6IKv
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score


#load the dataset
url = "https://github.com/mukta774/skin_care/blob/2c6f1651027a2a53cbfb494afb2a1335f281e744/Skin_Type_OG.csv"

skin_og = pd.read_csv(url)

#preview the dataset and check the info
print(skin_og.head())
print(skin_og.info())
print(skin_og.describe())

# Check for missing values
missing_values = skin_og.isnull().sum()
print("Missing values per column:")
print(missing_values)

#This covers histograms and count plots for key variables: Age, Gender, Skin Type, Hydration Level, and Oil Level to help visualize their distributions clearly.
# Set visualization style
sns.set(style='whitegrid')

# Plot distribution of Age
plt.figure(figsize=(8, 6))
sns.histplot(skin_og['Age'], bins=30, kde=True, color='blue')
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

#Plot count of Gender
plt.figure(figsize=(8, 6))
sns.countplot(x='Gender', data=skin_og, palette='pastel')
plt.title('Count of Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

#Plot distribution of Skin Type
plt.figure(figsize=(8, 6))
sns.countplot(x='Skin_Type', data=skin_og, palette='Set2')
plt.title('Distribution of Skin Type')
plt.xlabel('Skin Type')
plt.ylabel('Count')
plt.show()

#Plot distribution of Hydration Level
plt.figure(figsize=(8, 6))
sns.countplot(x='Hydration_Level', data=skin_og, palette='cool')
plt.title('Distribution of Hydration Level')
plt.xlabel('Hydration Level')
plt.ylabel('Count')
plt.show()

# Plot distribution of Oil Level
plt.figure(figsize=(8, 6))
sns.countplot(x='Oil_Level', data=skin_og, palette='coolwarm')
plt.title('Distribution of Oil Level')
plt.xlabel('Oil Level')
plt.ylabel('Count')
plt.show()

# Select numerical columns
numeric_cols = skin_og.select_dtypes(include=['int64', 'float64']).columns

# Calculate correlation matrix for numerical variables
correlation_matrix = skin_og[numeric_cols].corr()
print("Correlation Matrix:\n", correlation_matrix)

# Plot correlation matrix heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix of Numerical Variables')
plt.show()

# Create scatter plot matrix for numerical variables
sns.pairplot(skin_og[numeric_cols])
plt.suptitle('Scatter Plot Matrix for Numerical Variables', y=1.02)
plt.show()

# Encode categorical variables to numeric
categorical_cols = ['Gender', 'Hydration_Level', 'Oil_Level', 'Sensitivity']
skin_og_encoded = skin_og.copy()

for col in categorical_cols:
    le = LabelEncoder()
    skin_og_encoded[col] = le.fit_transform(skin_og_encoded[col])

# Encode target variable Skin_Type
target_le = LabelEncoder()
skin_og_encoded['Skin_Type'] = target_le.fit_transform(skin_og_encoded['Skin_Type'])

# Split features and target
X = skin_og_encoded.drop('Skin_Type', axis=1)
y = skin_og_encoded['Skin_Type']

# Split into train-test sets (80-20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)


# Instantiate Logistic Regression for multiclass classification
model = LogisticRegression(max_iter=5000, solver='saga')

# Train the model
model.fit(X_train, y_train)



# Predictions on test data
y_pred = model.predict(X_test)

# Accuracy
print(f"Accuracy on test set: {accuracy_score(y_test, y_pred):.4f}")

# Classification report for precision, recall, f1-score
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=target_le.classes_))

# Confusion matrix heatmap
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=target_le.classes_,
            yticklabels=target_le.classes_, cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()



# Correlation matrix
numeric_cols = skin_og_encoded.select_dtypes(include=['int64', 'float64']).columns
correlation_matrix = skin_og_encoded[numeric_cols].corr()

plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix of Numerical Variables')
plt.show()

# Scatter plot matrix
sns.pairplot(skin_og_encoded[numeric_cols])
plt.suptitle('Scatter Plot Matrix for Numerical Variables', y=1.02)
plt.show()

# Apply cross-validation and print metrics
cv_accuracy_scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')
cv_f1_scores = cross_val_score(model, X, y, cv=5, scoring='f1_weighted')
cv_precision_scores = cross_val_score(model, X, y, cv=5, scoring='precision_weighted')
cv_recall_scores = cross_val_score(model, X, y, cv=5, scoring='recall_weighted')


print(f"Cross-validation accuracy scores: {cv_accuracy_scores}")
print(f"Mean cross-validation accuracy: {cv_accuracy_scores.mean():.4f}")
print(f"Cross-validation F1 scores: {cv_f1_scores}")
print(f"Mean cross-validation F1 score: {cv_f1_scores.mean():.4f}")
print(f"Cross-validation Precision scores: {cv_precision_scores}")
print(f"Mean cross-validation Precision score: {cv_precision_scores.mean():.4f}")
print(f"Cross-validation Recall scores: {cv_recall_scores}")
print(f"Mean cross-validation Recall score: {cv_recall_scores.mean():.4f}")

import pandas as pd # Import pandas

# Example of new input data for prediction
# Replace these values with your desired input
new_data = {
    'Age': [35],
    'Gender': ['Female'],
    'Hydration_Level': ['Medium'],
    'Oil_Level': ['High'],
    'Sensitivity': ['Medium'],
    'Humidity': [65.0],
    'Temperature': [23.5]
}

new_df = pd.DataFrame(new_data)

# Preprocess the new data using the same LabelEncoders as used during training
# Ensure the order of columns matches the training data
new_df_encoded = new_df.copy()

# Access the encoders used in the training cell
# Assuming 'categorical_cols' and the individual 'le' objects for each column
# are available from the previous cell's execution context.
# If not, you might need to re-fit or load the encoders.

# To ensure correct encoding, iterate through the categorical columns and apply the corresponding encoder
for col in categorical_cols:
    try:
        # Find the encoder for the current column from the previous cell's context
        # This assumes the encoders were stored in a way that they can be accessed here.
        # A better approach in a real scenario would be to save and load the encoders.
        # For this example, we'll assume the le object from the previous loop is still accessible
        # and apply it to the correct column. This is a simplification.
        # The previous code used a single 'le' which is incorrect for multiple columns.
        # We need to ensure the encoder for 'Gender' is used for 'Gender', etc.

        # A robust way would be to store encoders in a dictionary:
        # encoders = {col: LabelEncoder().fit(skin_og[col]) for col in categorical_cols}
        # Then use: new_df_encoded[col] = encoders[col].transform(new_df_encoded[col])

        # Since the original code didn't store encoders in a dictionary, we'll use a simplified approach
        # and re-initialize LabelEncoder for each column for demonstration purposes.
        # NOTE: This is not ideal if the test set has categories not seen in the training set.
        # A proper solution involves saving/loading the fitted encoders.

        temp_le = LabelEncoder()
        # Fit on combined data to handle potential new categories in new_df
        # This is a workaround for demonstration; ideally, fit on training data only and handle unknown
        temp_le.fit(skin_og[col])
        new_df_encoded[col] = temp_le.transform(new_df_encoded[col])

    except ValueError as e:
        print(f"Error encoding column {col}: {e}")
        # You might want to handle unseen categories here, e.g., by setting to NaN or a default value
        # For now, we'll re-raise the error
        raise e


# Ensure the columns are in the same order as the training data
new_df_encoded = new_df_encoded[X_train.columns]

# Make predictions using the trained model
predicted_skin_type_encoded = model.predict(new_df_encoded)

# Decode the predicted skin type back to the original labels
predicted_skin_type = target_le.inverse_transform(predicted_skin_type_encoded)

print(f"The predicted skin type for the input data is: {predicted_skin_type[0]}")

from google.colab import drive
drive.mount('/content/drive')
